var main=angular.module('main',[]);

main.controller("mainCtrl", function ($scope){ 
    
    $scope.header = "Problem Solving: 'Improvise, Adapt and Overcome'";
    
    var codeWord = {descrip: "Accept your secret mission by strategically entering vowels during Code Word.", pic: "Images/usmc1.JPG", caption: "'NEW YORK, N.Y. - Staff Sgt. Raymond Brown, with Special Purpose Marine Air-Ground Task Force Fleet Week New York, watches the Manhattan Bridge and New York pass below on a flight to Marine Day at Prospect Park in Brooklyn, New York, May 26. Now in its 30th year, Fleet Week is the city's time-honored celebration of the sea services. It is an unparalleled opportunity for the citizens of New York and the surrounding tri-state area to meet Marines, Sailors, and Coast Guardsmen, as well as witness firsthand the latest capabilities of today's maritime services.' --Marines.mil "};
    var sumPuzzles = {descrip: "Avert disaster by arranging numbers in a winning combination during Sum Puzzles.", pic: "Images/usmc2.JPG", caption: "'U.S. FIFTH FLEET AREA OF OPERATIONS - U.S. FIFTH FLEET AREA OF OPERATIONS (Dec. 22, 2017) - A Sailor with USS San Diego observes USNS Washington Chambers during a replenishment at sea. San Diego, with the embarked 15th Marine Expeditionary Unit, is deployed to the U.S. 5th Fleet area of operations in support of maritime security operations to reassure allies and partners and preserve the freedom of navigation and the free flow of commerce in the region. ' -- Marines.mil"};
    var numberGuess = {descrip: "Foil villainous plots by strategically bisecting numeric intervals during Number Guess.", pic: "Images/usmc3.JPG", caption: "'Naval Air Station Sigonella, Italy - An Explosive Ordnance Disposal technician assigned to Special Purpose Marine Air-Ground Task Force-Crisis Response-Africa controls a bomb disposal robot during non-combatant evacuation operation training aboard Naval Air Station Sigonella, Italy, on Nov. 17, 2017. SPMAGTF-CR-AF deployed to conduct limited crisis-response and theater-security operation in Europe and Africa. ' --Marines.mil"};
    var war = {descrip: "Achieve victory with correct quantitative comparisons during War.", pic: "Images/usmc4.JPG", caption: "'FORT A.P. HILL, Va. - A Marine with Battalion Landing Team, 1st Battalion, 2nd Marines, 22nd Marine Expeditionary Unit fast ropes out of an MV-22 Osprey during the 22nd MEU Deployment for Training at Fort A.P. Hill, VA., July 31, 2018. In preparation for their upcoming deployment, the Marines practiced embassy reinforcement by fast roping onto a rooftop and clearing out a simulated embassy building, which in turn allowed the Marines to train in an urban environment.' --Marines.mil "};
    
    $scope.descripPic = [codeWord, sumPuzzles, numberGuess, war];
       
});